spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}


spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1
server.max-http-request-size=-1
server.tomcat.max-http-form-post-size=-1
server.tomcat.max-swallow-size=-1
